version: '3'

services:
  dynamodb-local:
    container_name: test_dynamodb-local
    image: amazon/dynamodb-local:latest
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    volumes:
      - dynamodb-local-data:/data
    ports:
      - 8000:8000
    networks:
      - dynamodb-local-network

  dynamodb-admin:
    container_name: test_dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
    networks:
      - dynamodb-local-network

  terraform:
    container_name: test_dynamodb-terraform
    image: hashicorp/terraform:1.0.3
    command: >
        /bin/sh -c
        '
        echo "plugin_cache_dir = \"/root/.terraform.d/plugin-cache\"" > ~/.terraformrc &&
        terraform init &&
        terraform apply -auto-approve;
        /bin/sh
        '
    entrypoint: ''
    tty: true
    environment:
        - AWS_ACCESS_KEY_ID=dummy
        - AWS_SECRET_ACCESS_KEY=dummy
    working_dir: /terraform/environment/local
    volumes:
        - ./infra:/terraform
    depends_on:
        - dynamodb-local
    networks:
        - dynamodb-local-network

volumes:
  dynamodb-local-data:
  infra:

networks:
  dynamodb-local-network:
    driver: bridge